# Generated by Django 2.0.3 on 2018-08-29 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0064_productvariant_handle_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.BooleanField(default=False)),
                ('top_seller', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='product.Product')),
            ],
            options={
                'permissions': (('view', 'Can view product extensions'), ('edit', 'Can edit product extensions')),
            },
        ),
    ]
